### ISSUE TITLE
Android no performance data

### ISSUE THREAD

**Issue by Wingee** [hansemannn/titanium-firebase-performance#2]
Is there anything I can do to see if the performance data for Android is working?
I've implemented in both iOS and Android.

iOS shows network performance data in the Firebase console but Android doesn't show any.

I've also tried starting and stopping a trace but I'm not seeing any data in Firebase.

Any ideas what else I can look at to investigate why i'm not getting any performance data?

Thanks

**Comment by anik786** [comment]
Could it be because the firebase-perf library being used is out of date:
https://github.com/hansemannn/titanium-firebase-performance/blob/master/android/lib/firebase-perf-11.0.4.aar

It looks like we are using firebase-perf v11.0.4, while the latest version is v16.0.0, as described here: https://firebase.google.com/docs/perf-mon/get-started-android?authuser=0.

**Comment by Wingee** [comment]
Thanks @anik786 I've added the 16.0.0.aar file, recompiled the module and tried that but to no avail. I'm still not seeing any data in the Firebase console. 

I'm running adb logcat -s FirebasePerformance and not seeing anything in there either, so something in this module is not working.

**Comment by anik786** [comment]
I'm not sure then. I really hoping this issue gets fixed soon. Otherwise this plugin is useless for Android, which would be a shame.

**Comment by anik786** [comment]
Any update on this?

**Comment by phillipmovista** [comment]
I am trying to get this to work on Titanium SDK 9.3.2.GA for Android and the app will not even load.

I tried to checkout the code and use updated firebase-perf code, but for some reason that compile was not playing well either.

Is there any plan to work on getting this piece available to work in Ti 9+?

**Comment by hansemannn** [comment]
I think this is not an issue anymore. If it is, feel free to reopen and we'll take a closer look!
