### ISSUE TITLE
Including performance module on iOS fails build with linker error

### ISSUE THREAD

**Issue by raybelisle** [hansemannn/titanium-firebase-performance#3]
Using TiSDK 7.5.0
firebase core 2.2.0
firebase performance 1.1.1

Using just a blank new project. Not referencing any of the modules in the code yet, just trying to include the modules in the build. The build fails with a linker error from xCode. Not sure what to do at this point?

**Comment by hansemannn** [comment]
The native libs probably need to be updated. You can download them from Firebase and copy them to platform/. Then you can do a pull request. Thanks!

**Comment by raybelisle** [comment]
Did that, compiles properly but when I try to include it in my project I get the error:

`Undefined symbols for architecture x86_64:
[TRACE]    "_OBJC_CLASS_$_FIRAppEnvironmentUtil", referenced from:
[TRACE]        objc-class-ref in FirebaseRemoteConfig(RCNConfigSettings_f35ba384ea3fae7ae993980d5fde4689.o)
[TRACE]        objc-class-ref in FirebaseRemoteConfig(RCNDevice_0dfa3bc8d2d077d72521a108a2296745.o)
[TRACE]    "_OBJC_CLASS_$_FIRAScreenViewReporter", referenced from:
[TRACE]        objc-class-ref in FirebasePerformance(FPRScreenTraceTracker_084c2653f4b55286a1c9db2eaf78e5e9.o)
[TRACE]  ld: symbol(s) not found for architecture x86_64
[TRACE]  clang: error: 
[TRACE]  linker command failed with exit code 1 (use -v to see invocation)
[ERROR]  ** BUILD FAILED **
`
Wish I understood module creation more, but no idea where to go from here...

**Comment by klaudia-dogfish** [comment]
Any progress on this issue guys?

**Comment by hansemannn** [comment]
This should not be an issue anymore.
